var flashcards =
    {
"Final Exam":
[
{"question": "What is the supreme law of the land?",
"answer": "The Constitution"},
{"question": "What does the Constitution do?",
"answer": "Sets up the government, defines the government, and protects basic rights of Americans"},
{"question": "The idea of self-government is in the first three words of the Constitution. What are these words?	",
"answer": "We the People"},
{"question": "What is an amendment?",
"answer": "A change or addition to the Constitution"},
{"question": "What do we call the first ten amendments to the Constitution?",
"answer": "The Bill of Rights"},
{"question": "What is one right or freedom from the First Amendment?",
"answer": {"type": "subset",
           "size": 1,
           "answers": ["Speech", "religion", "assembly", "press", "petition"]}},
 {"question": "How many amendments does the Constitution have?",
"answer": "Twenty-seven"},
{"question": "What did the Declaration of Independence do?",
"answer": "Announced our independence from Great Britain"},
{"question": "What are two rights in the Declaration of Independence?",
"answer": {"type": "subset",
           "size": 2,
           "answers": ["Life", "liberty", "the pursuit of happiness"]}},
{"question": "What is freedom of religion?",
"answer": "You can practice any religion or not practice a religion at all"},
{"question": "What is the economic system in the United States?",
"answer": "Capitalist and market economy"},
{"question": "What is the \"rule of law\"?",
"answer": "Everyone must follow the law even leaders and government because no one is above the law"},
{"question": "Name one branch or part of the government.",
"answer": {"type": "subset", 
           "size": 1,
           "answers": ["Legislative", "Executive", "Judicial"]}},
{"question": "What stops one branch of government from becoming too powerful?",
"answer": "The separation of powers and checks and balances"},
{"question": "Who is in charge of the executive branch?",
"answer": "The President"},
{"question": "Who makes federal laws?",
"answer": "Congress"},
{"question": "What are the two parts of the U.S. Congress?",
"answer": {"type": "multi-part",
           "answers": ["The Senate", "the House of Representatives"]}},
{"question": "How many U.S. Senators are there?",
"answer": "One hundred"},
{"question": "We elect a U.S. Senator for how many years? ",
"answer": "Six years"},
{"question": "Who is one of your state's U.S. Senators now?*",
"answer": {"type": "subset",
           "size": 1,
           "answers": ["Orrin Hatch", "Mike Lee"]}},
{"question": "The House of Representatives has how many voting members? ",
"answer": "Four hundred thirty-five"},
{"question": "We elect a U.S. Representative for how many years?",
"answer": "Two years"},
{"question": "Name your U.S. Representative.*",
"answer": "Mia Love"},
{"question": "Who does a U.S. Senator represent?",
"answer": "All the people living in the state"},
{"question": "Why do some states have more Representatives than other states?",
"answer": "Because of the state's population, some states have more people"},
{"question": "We elect a President for how many years?",
"answer": "Four years and up to two terms"},
{"question": "In what month do we vote for President?",
"answer": "November"},
{"question": "What is the name of the President of the United States now?*",
"answer": "Donald Trump"},
{"question": "What is the name of the Vice President of the United States now?*",
"answer": "Mike Pence"},
{"question": "If the President can no longer serve, who becomes President?",
"answer": "The Vice President"},
{"question": "If both the President and the Vice President can no longer serve, who becomes President?",
"answer": "The Speaker of the House"},
{"question": "Who is the Commander in Chief of the military?",
"answer": "The President"},
{"question": "Who signs bills to become laws?",
"answer": "The President"},
{"question": "Who vetoes bills?",
"answer": "The President"},
{"question": "What does the President's Cabinet do?",
"answer": "Advises the President"},
           {"question": "What are two Cabinet-level positions?",
            "answer": {"type": "subset",
                       "size": 2,
                       "answers": ["Secretary of Agriculture", "Secretary of Commerce", "Secretary of Defense", "Secretary of Education", "Secretary of Energy", "Secretary of Health and Human Services", "Secretary of Homeland Security", "Secretary of Housing and Urban Development", "Secretary of Interior", "Secretary of Labor", "Secretary of State", "Secretary of Transportation", "Secretary of Treasury", "Secretary of Veterans' Affairs", "Attorney General", "Vice President"]}},
           {"question": "What does the judicial branch do?",
            "answer": {"type": "multi-part",
                       "answers": ["Reviews and explains laws", "Resolves disagreements", "Decides if a law is unconstitutional"]}},
{"question": "What is the highest court in the United States?",
"answer": "The Supreme Court"},
{"question": "How many justices are on the Supreme Court?",
"answer": "Nine"},
{"question": "Who is the Chief Justice of the United States now?*",
"answer": "John Roberts"},
    {"question": "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["To print money", "To declare war", "To create an army", "To make treaties"]}},
    {"question": "Under our Constitution, some powers belong to the states. What is one power of the states? ",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["Provide schooling and education", "Provide protection (police)", "Provide safety (fire dept.)", "Give a driver's license", "Approve zoning and land use"]}},
{"question": "Who is the Governor of your state now?*",
"answer": "Gary Herbert"},
{"question": "What is the capital of your state?",
"answer": "Salt Lake City	"},
            {"question": "What are the two major political parties in the United States?",
             "answer": {"type": "multi-part",
                        "answers": ["Democratic", "Republican"]}},
{"question": "What is the political party of the President now?*",
"answer": "Republican"},
{"question": "What is the name of the Speaker of the House of Representatives now?*",
"answer": "Paul Ryan"},
           {"question": "There are four amendments to the Constitution about who can vote. Describe one of them.",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["Citizens 18 and older can vote", "You don't have to pay to vote", "Any citizen (male or female) can vote", "A citizen of any race can vote"]}},
           {"question": "What is one responsibility that is only for United States citizens?",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["Serve on a jury", "Vote in a federal election"]}},
           {"question": "Name one right only for United States citizens.",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["Vote in a federal election", "Run for federal office"]}},
           {"question": "What are two rights of everyone living in the United States?",
            "answer": {"type": "subset",
                       "size": 2,
                       "answers": ["Freedom of expression", "Freedom of speech", "Freedom of assembly", "Freedom of worship", "Freedom to petition the government", "The right to bear arms"]}},
           {"question": "What do we show loyalty to when we say the Pledge of Allegiance?",
            "answer": {"type": "multi-part", "answers": ["The United States", "The flag"]}},
{"question": "What is one promise you make when you become a United States citizen?",
"answer": {"type": "subset",
           "size": 1,
           "answers": ["Give up loyalty to other countries", "defend the laws and Constitution of the U.S.", "obey the laws of the U.S., serve in the U.S. military (if needed)", "serve the nation (if needed)", "or to be loyal to the U.S."]}},
{"question": "How old do citizens have to be to vote for President?",
"answer": "Eighteen-years-old or older"},
 {"question": "What are two ways that Americans can participate in their democracy?",
  "answer": {"type": "subset",
             "size": 2,
             "answers": ["Vote", "join a political party", "help with a campaign", "join a civic group", "join a community group", "give an elected official your opinion", "call Senators and Representatives", "publically support or oppose an issue", "run for office", "write to a newspaper"]}},
{"question": "When is the last day you can send in federal income tax forms?",
"answer": "April 15"},
{"question": "When must all men register for the Selective Service?",
"answer": "Between the ages of eighteen and twenty-six"},
{"question": "What is one reason colonists came to America?",
"answer": {"type": "subset", 
           "size": 1,
           "answers": ["Freedom", "political liberty", "religious freedom", "economic opportunity", "to practice their religion", "escape persecution"]}},
{"question": "Who lived in America before the Europeans arrived?",
"answer": "American Indians"},
{"question": "What group of people was taken to America and sold as slaves?",
"answer": "Africans"},
{"question": "Why did the colonists fight the British?",
"answer": {"type": "multi-part",
           "answers": ["High taxes (taxation without representation)", "The British army stayed in their houses (quartering)", "because they didn't have self-government"]}},
{"question": "Who wrote the Declaration of Independence?",
"answer": "Thomas Jefferson"},
{"question": "When was the Declaration of Independence adopted?",
"answer": "July 4, 1776"},
{"question": "There were 13 original states. Name three.",
"answer": {"type": "subset", 
           "size": 3,
           "answers": ["New Hampshire", "Massachusetts", "Rhode Island", "Connecticut", "New York", "New Jersey", "Pennsylvania", "Delaware", "Maryland", "Virginia", "North Carolina", "South Carolina", "Georgia"]}},
{"question": "What happened at the Constitutional Convention?",
"answer": "The Constitution was written"},
{"question": "When was the Constitution written?",
"answer": "1787"},
{"question": "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
 "answer": {"type": "subset",
            "size": 1,
            "answers": ["James Madison", "Alexander Hamilton", "John Jay", "Publius"]}},
{"question": "What is one thing Benjamin Franklin is famous for?",
"answer": {"type": "subset",
           "size": 1,
           "answers": ["U.S. diplomat", "oldest member of Constitutional Convention", "first Postmaster General", "author of \"Poor Richard's Almanac\"", "started the first free libraries"]}},
{"question": "Who is the \"Father of Our Country\"?",
"answer": "George Washington"},
{"question": "Who was the first President?",
"answer": "George Washington"},
{"question": "What territory did the United States buy from France in 1803?",
"answer": "The Louisiana Territory"},
 {"question": "Name one war fought by the United States in the 1800s.",
  "answer": {"type": "subset", 
             "size": 1,
             "answers": ["War of 1812", "Mexican-American War", "Spanish-American War", "Civil War"]}},
{"question": "Name the U.S. war between the North and the South. ",
"answer": "The Civil War"},
            {"question": "Name one problem that led to the Civil War.",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["Slavery", "economic reasons", "states' rights"]}},
 {"question": "What was one important thing that Abraham Lincoln did?",
  "answer": {"type": "subset", 
             "size": 1,
             "answers": ["Freed the slaves", "saved the Union", "led the U.S. during the Civil War"]}},
{"question": "What did the Emancipation Proclamation do?",
"answer": "Freed slaves in the Confederate States"},
{"question": "What did Susan B. Anthony do?",
"answer": "Fought for women's and civil rights"},
            {"question": "Name one war fought by the United States in the 1900s.",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["World War I", "World War II", "Korean War", "Vietnam War", "Persian Gulf War"]}},
{"question": "Who was President during World War I?",
"answer": "Woodrow Wilson"},
{"question": "Who was President during the Great Depression and World War II? ",
"answer": "Franklin Delano Roosevelt"},
            {"question": "Who did the United States fight in World War II?",
             "answer": {"type": "multi-part",
                        "answers": ["Japan", "Germany", "Italy"]}},
{"question": "Before he was President, Eisenhower was a general. What war was he in?",
"answer": "World War II"},
{"question": "During the Cold War, what was the main concern of the United States?",
"answer": "Communism"},
{"question": "What movement tried to end racial discrimination?",
"answer": "The Civil Rights Movement"},
{"question": "What did Martin Luther King, Jr. do?",
"answer": "ought for civil rights and equality for all Americans"},
{"question": "What major event happened on September 11, 2001, in the United States?",
"answer": "Terrorists attacked the United States"},
 {"question": "Name one American Indian tribe in the United States.",
  "answer": {"type": "subset", 
             "size": 1,
             "answers": ["Cherokee", "Navajo", "Sioux", "Chippewa", "Choctaw", "Pueblo", "Apache", "Iroquois", "Creek", "Blackfeet", "Seminole", "Cheyenne", "Arawak", "Shawnee", "Mohegan", "Huron", "Oneida", "Lakota", "Crow", "Teton", "Hopi","Inuit"]}},
{"question": "Name one of the two longest rivers in the United States.",
"answer": {"type": "subset",
           "size": 1,
           "answers": ["Missouri River", "Mississippi River"]}},
{"question": "What ocean is on the West Coast of the United States?",
"answer": "Pacific Ocean"},
{"question": "What ocean is on the East Coast of the United States?",
"answer": "Atlantic Ocean"},
{"question": "Name one U.S. territory.",
"answer": {"type": "subset", 
           "size": 1,
           "answers": ["Puerto Rico", "U.S. Virgin Islands", "American Samoa", "Northern Mariana Islands", "Guam"]}},
{"question": "Name one state that borders Canada.",
 "answer": {"type": "subset",
            "size": 1,
            "answers": ["Maine", "New Hampshire", "Vermont", "New York", "Pennsylvania", "Ohio", "Michigan", "Minnesota", "North Dakota", "Montana", "Idaho", "Washington", "Alaska"]}},
{"question": "Name one state that borders Mexico.",
 "answer": {"type": "subset", 
            "size": 1,
            "answers": ["California", "Arizona", "New Mexico", "Texas"]}},
{"question": "What is the capital of the United States?",
"answer": "Washington D.C."},
{"question": "Where is the Statue of Liberty?",
"answer": "In New York Harbor on Liberty Island"},
{"question": "Why does the flag have 13 stripes?",
"answer": "Because of the thirteen original colonies"},
{"question": "Why does the flag have 50 stars?",
"answer": "There is one star for each state and 50 states in the Union"},
{"question": "What is the name of the national anthem?",
"answer": "The Star Spangled Banner"},
{"question": "When do we celebrate Independence Day?",
"answer": "July 4"},
{"question": "Name two national U.S. holidays.",
"answer": {"type": "subset",
           "size": 2,
           "answers": ["New Year's Day", "Martin Luther King, Jr. Day", "Presidents' Day", "Memorial Day", "Independence Day", "Labor Day", "Columbus Day", "Veterans' Day", "Thanksgiving", "Christmas"]}}
],
"Test 12":
[{"question": "What movement tried to end racial discrimination?",
"answer": "The Civil Rights Movement"},
{"question": "What were Lewis and Clark searching for?",
"answer": "A water way between the Atlantic and Pacific Oceans"},
{"question": "Who was President during ,the Great Depression and World War II? ",
"answer": "Franklin Delano Roosevelt"},
{"question": "What did the Emancipation Proclamation do?",
"answer": "Freed slaves in the Confederate States"},
{"question": "Name one purpose of the United Nations.",
"answer": {"type": "subset",
           "size": 1,
           "answers": ["For countries to discuss and try to resolve world problems", "to provide economic aid to many countries"]}},
{"question": "What is one promise you make when you become a United States citizen?",
"answer": {"type": "subset",
           "size": 1,
           "answers": ["Give up loyalty to other countries", "defend the laws and Constitution of the U.S.", "obey the laws of the U.S., serve in the U.S. military (if needed)", "serve the nation (if needed)", "or to be loyal to the U.S."]}},
{"question": "Name one problem that led to the Civil War.",
"answer": "Slavery or economic reasons or states' rights"},
{"question": "How old do citizens have to, be to vote for President?",
"answer": "Eighteen-years-old or older"},
 {"question": "What are two ways that Americans can participate in their democracy?",
  "answer": {"type": "subset",
             "size": 2,
             "answers": ["Vote", "join a political party", "help with a campaign", "join a civic group", "join a community group", "give an elected official your opinion", "call Senators and Representatives", "publically support or oppose an issue", "run for office", "write to a newspaper"]}},
{"question": "What were the names of the armies that fought in the Civil War?",
"answer": "The Union and the Confederacy"},
{"question": "When is the last day you can send in federal income tax forms?",
"answer": "April 15"},
{"question": "Who was President during World War I?",
 "answer": "Woodrow Wilson"},
 {"question": "What was one important thing that Abraham Lincoln did?",
  "answer": {"type": "subset", 
             "size": 1,
             "answers": ["Freed the slaves", "saved the Union", "led the U.S. during the Civil War"]}},
 {"question": "Name one American Indian tribe in the United States.",
  "answer": {"type": "subset", 
             "size": 1,
             "answers": ["Cherokee", "Navajo", "Sioux", "Chippewa", "Choctaw", "Pueblo", "Apache", "Iroquois", "Creek", "Blackfeet", "Seminole", "Cheyenne", "Arawak", "Shawnee", "Mohegan", "Huron", "Oneida", "Lakota", "Crow", "Teton", "Hopi","Inuit"]}},
 {"question": "When must all men register for the Selective Service?",
  "answer": "Between the ages of eighteen and twenty-six"},
 {"question": "What territory did the United States buy from France in 1803?",
  "answer": "The Louisiana Territory"},
 {"question": "What is the Selective Service?",
  "answer": "An agency that gathers information on people eligible for military service in case there is need for conscription"},
 {"question": "Name one war fought by the United States in the 1800s.",
  "answer": {"type": "subset", 
             "size": 1,
             "answers": ["War of 1812", "Mexican-American War", "Spanish-American War", "Civil War"]}},
 {"question": "What did Martin Luther King, Jr. do?",
  "answer": "Fought for civil rights and equality for all Americans"}
],
"Quiz 17":
        [
            {"question": "Name one war fought by the United States in the 1900s.",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["World War I", "World War II", "Korean War", "Vietnam War", "Persian Gulf War"]}},
            {"question": "Who was President during World War I?",
             "answer": "Woodrow Wilson"},
            {"question": "Who was President during the Great Depression and World War II? ",
             "answer": "Franklin Delano Roosevelt"},
            {"question": "Who did the United States fight in World War II?",
             "answer": {"type": "multi-part",
                        "answers": ["Japan", "Germany", "Italy"]}},
            {"question": "Before he was President, Eisenhower was a general. What war was he in?",
             "answer": "World War 2"},
            {"question": "Name one purpose of the United Nations.",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["For countries to discuss and try to resolve world problems", "To provide economic aid to many countries"]}},
            {"question": "During the Cold War, what was the main concern of the United States?",
             "answer": "Communism"},
            {"question": "What movement tried to end racial discrimination?",
             "answer": "The Civil Rights Movement"},
            {"question": "What did Martin Luther King, Jr. do?",
             "answer": "Fought for civil rights and equality for all Americans"},
            {"question": "What major event happened on September 11, 2001, in the United States?",
             "answer": "Terrorists attacked the United States"}
        ],
        "Test 11": 
        [
            {"question": "What were Lewis and Clark searching for?",
             "answer": "A water way between the Atlantic and Pacific Oceans"},
            {"question": "What did the Emancipation Proclamation do?",
             "answer": "Freed slaves in the Confederate States"},
            {"question": "What is one promise you make when you become a United States citizen?",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["Give up loyalty to other countries", "defend the laws and Constitution of the U.S.", "obey the laws of the U.S.", "serve in the U.S. military (if needed)", "serve the nation (if needed)", "to be loyal to the U.S."]}},
            {"question": "Name one problem that led to the Civil War.",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["Slavery", "economic reasons", "states' rights"]}},
            {"question": "How old do citizens have to be to vote for President?",
             "answer": "Eighteen-years-old or older"},
            {"question": "What are two ways that Americans can participate in their democracy?",
             "answer": {"type": "subset",
                        "size": 2,
                        "answers": ["Vote", "join a political party", "help with a campaign", "join a civic group", "join a community group", "give an elected official your opinion", "call Senators and Representatives", "publically support or oppose an issue", "run for office", "write to a newspaper"]}},
            {"question": "What were the names of the armies that fought in the Civil War?",
             "answer": {"type": "multi-part",
                        "answers": ["The Union", "the Confederacy"]}},
            {"question": "When is the last day you can send in federal income tax forms?",
             "answer": "April 15"},
            {"question": "What was one important thing that Abraham Lincoln did?",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["the slaves", "saved the Union", "led the U.S. during the Civil War"]}},
            {"question": "Name one American Indian tribe in the United States.",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["Cherokee", "Navajo", "Sioux", "Chippewa", "Choctaw", "Pueblo", "Apache", "Iroquois", "Creek", "Blackfeet", "Seminole", "Cheyenne", "Arawak", "Shawnee", "Mohegan", "Huron", "Oneida", "Lakota", "Crow", "Teton", "Hopi", "Inuit"]}},
            {"question": "When must all men register for the Selective Service?",
             "answer": "Between the ages of eighteen and twenty-six"},
            {"question": "What territory did the United States buy from France in 1803?",
             "answer": "The Louisiana Territory"},
            {"question": "What is the Selective Service?",
             "answer": "An agency that gathers information on people eligible for military service in case there is need for conscription"},
            {"question": "Name one war fought by the United States in the 1800s.",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["War of 1812", "Mexican-American War", "Spanish-American War", "Civil War"]}},
            {"question": "In what month do we vote for the new President?",
             "answer": "November"},
            {"question": "What did Susan B. Anthony do?",
             "answer": "Fought for women's and civil rights"},
            {"question": "Name the U.S. war between the North and the South. ",
             "answer": "The Civil War"},
            {"question": "What are the two major political parties in the United States?",
             "answer": {"type": "multi-part",
                        "answers": ["Democratic", "Republican"]}}
        ],
        "Quiz 16":
        [
            {"question": "What territory did the United States buy from France in 1803?",
             "answer": "The Louisiana Territory"},
            {"question": "What were Lewis and Clark searching for?",
             "answer": "A water way between the Atlantic and Pacific Oceans"},
            {"question": "Name one war fought by the United States in the 1800s.",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["War of 1812", "Mexican-American War", "Spanish-American War", "Civil War"]}},
            {"question": "Name the U.S. war between the North and the South. ",
             "answer": "The Civil War"},
            {"question": "Name one problem that led to the Civil War.",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["Slavery", "economic reasons", "states' rights"]}},
            {"question": "What was one important thing that Abraham Lincoln did?",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["Freed the slaves", "saved the Union", "Led the U.S. during the Civil War"]}},
            {"question": "What did the Emancipation Proclamation do?",
             "answer": "Freed slaves in the Confederate States"},
            {"question": "What did Susan B. Anthony do?",
             "answer": "Fought for women's and civil rights"},
            {"question": "What were the names of the armies that fought in the Civil War?",
             "answer": {"type": "multi-part",
                        "answers": ["The Union", "the Confederacy"]}},
            {"question": "Name one American Indian tribe in the United States.",
             "answer": {"type": "subset",
                        "size": 1,
                        "answers": ["Cherokee", "Navajo", "Sioux", "Chippewa", "Choctaw", "Pueblo", "Apache", "Iroquois", "Creek", "Blackfeet", "Seminole", "Cheyenne", "Arawak", "Shawnee", "Mohegan", "Huron", "Oneida", "Lakota", "Crow", "Teton", "Hopi", "Inuit"]}}
        ],
        "Quiz 15":
        [{"question": "What is one promise you make when you become a United States citizen?",
          "answer": {"type": "subset",
                     "size": 1,
                     answers: ["Give up loyalty to other countries", "Defend the laws and Constitution of the U.S.", "Obey the laws of the U.S.", "Serve in the U.S. military (if needed)", "Serve the nation (if needed)", "To be loyal to the U.S."]}},
         {"question": "How old do citizens have to be to vote for President?",
          "answer": "Eighteen-years-old or older"},
         {"question": "What are two ways that Americans can participate in their democracy?",
          "answer": {"type": "subset",
                     "size": 2,
                     "answers": ["Vote", "Join a political party", "Help with a campaign", "Join a civic group", "Join a community group", "Give an elected official your opinion", "Call Senators and Representatives", "Publically support or oppose an issue", "Run for office", "Write to a newspaper"]}},
         {"question": "When is the last day you can send in federal income tax forms?",
          "answer": "April 15"},
         {"question": "When must all men register for the Selective Service?",
          "answer": "Between the ages of eighteen and twenty-six"},
         {"question": "What is the Selective Service?",
          "answer": "An agency that gathers information on people eligible for military service in case there is need for conscription"},
         {"question": "In what month do we vote for the new President?",
          "answer": "November"},
         {"question": "What are the two major political parties in the United States?",
          "answer": {"type": "multi-part",
                     "answers": ["Democratic", "Republican"]}}
          ],
          "Test 10":
          [{"question": "Who is the Governor of your state now?",
            "answer": "Gary Herbert"},
           {"question": "What are some of the requirements to be eligible to become President?",
            "answer": {"type": "multi-part",
                       "answers": ["Must be at least thirty-five-years-old", "Must have been born in the U.S.", "Must have lived in the U.S. for at least fourteen years"]}},
           {"question": "What do we show loyalty to when we say the Pledge of Allegiance?",
            "answer": {"type": "multi-part", "answers": ["The United States", "The flag"]}},
           {"question": "How many justices are on the Supreme Court?",
            "answer": "Nine"},
           {"question": "What are the two major political parties in the United States?",
            "answer": {"type": "multi-part",
                       "answers": ["Democratic", "Republican"]}},
           {"question": "Who is the Chief Justice of the United States now?",
            "answer": "John Roberts"},
           {"question": "Under our Constitution, some powers belong to the states. What is one power of the states? ",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["Provide schooling and education", "Provide protection (police)", "Provide safety (fire dept.)", "Give a driver's license", "Approve zoning and land use"]}},
           {"question": "Name the highest part of the Judiciary Branch of government.",
            "answer": "The Supreme Court"},
           {"question": "What is the name of the President's official home?",
            "answer": "The White House"},
           {"question": "There are four amendments to the Constitution about who can vote. Describe one of them.",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["Citizens 18 and older can vote", "You don't have to pay to vote", "Any citizen (male or female) can vote", "A citizen of any race can vote"]}},
           {"question": "In what month do we vote for President?",
            "answer": "November"},
           {"question": "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["To print money", "To declare war", "To create an army", "To make treaties"]}},
           {"question": "What is the highest court in the United States?",
            "answer": "The Supreme Court"},
           {"question": "What is the political party of the President now?",
            "answer": "Republican"},
           {"question": "In what month is the new President inaugurated?",
            "answer": "January"},
           {"question": "What does the President's Cabinet do?",
            "answer": "Advises the President"},
           {"question": "What is the name of the President of the United States now?",
            "answer": "Donald Trump"},
           {"question": "Name the amendments that guarantee or address voting rights.",
            "answer": {"type": "multi-part",
                       "answers": ["15", "19", "24"]}},
           {"question": "What is one responsibility that is only for United States citizens?",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["Serve on a jury", "Vote in a federal election"]}},
           {"question": "What is the name of the Vice President of the United States now?",
            "answer": "Mike Pence"},
           {"question": "What are two rights of everyone living in the United States?",
            "answer": {"type": "subset",
                       "size": 2,
                       "answers": ["Freedom of expression", "Freedom of speech", "Freedom of assembly", "Freedom of worship", "Freedom to petition the government", "The right to bear arms"]}},
           {"question": "Who nominates judges for the Supreme Court?",
            "answer": "The President"},
           {"question": "What is the head executive of a city government called?",
            "answer": "Mayor"},
           {"question": "If the President can no longer serve, who becomes President?",
            "answer": "The Vice President"},
           {"question": "What is the name of the Speaker of the House of Representatives now?",
            "answer": "Paul Ryan"},
           {"question": "What are two Cabinet-level positions?",
            "answer": {"type": "subset",
                       "size": 2,
                       "answers": ["Secretary of Agriculture", "Secretary of Commerce", "Secretary of Defense", "Secretary of Education", "Secretary of Energy", "Secretary of Health and Human Services", "Secretary of Homeland Security", "Secretary of Housing and Urban Development", "Secretary of Interior", "Secretary of Labor", "Secretary of State", "Secretary of Transportation", "Secretary of Treasury", "Secretary of Veterans' Affairs", "Attorney General", "Vice President"]}},
           {"question": "What is the capital of your state?",
            "answer": "Salt Lake City"},
           {"question": "If both the President and the Vice President can no longer serve, who becomes President?",
            "answer": "The Speaker of the House"},
           {"question": "What does the judicial branch do?",
            "answer": {"type": "multi-part",
                       "answers": ["Reviews and explains laws", "Resolves disagreements", "Decide if a law is unconstitutional"]}},
           {"question": "What is the head executive of a state government called?",
            "answer": "Governor"},
           {"question": "Name one right only for United States citizens.",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["Vote in a federal election", "Run for federal office"]}},
           {"question": "Where is the White House located?",
            "answer": "Washington D.C."},
           {"question": "Name one benefit of being a citizen of the United States.",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["To be able to attain Federal government jobs", "To be able to travel with a U.S. passport", "To be able to petition for close relatives to come live in the U.S."]}},
           {"question": " Who is the Commander-in-Chief of the military?",
            "answer": "The President"}],
          "Test 9":
          [{"question": "Name the amendments that guarantee or address voting rights",
            "answer": {"type": "multi-part",
                       "answers": ["15", "19", "24"]}},
           {"question":  "Who is the Chief Justice of the Supreme Court now?",
            "answer": "John Roberts"},
           {"question": "Name one right only for United States Citizens",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["Vote in a federal election", "Run for federal office"]}},
           {"question": "Under our Constitution some powers belong to the Federal Government.  What is one power of the federal government?",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["To print money",
                                   "To declare wars",
                                   "To create an army",
                                   "To make treaties"]}},
           {"question": "Under our Constitution some powers belong to the states.  What is one power of the states?",
            "answer": {"type": "subset",
                       "size": 1,
                       "answers": ["provide schooling and education",
                                   "Provide protection (police)",
                                   "Provide safety (fire department)",
                                   "give a drivers license",
                                   "approve zoning and land use"]}},
           {"question": "What is the head executive of a city government called?",
            "answer": "Mayor"},
           {"question": "Who do we show loyalty to when we say the Pledge of Allegiance?",
            "answer": {"type": "multi-part",
                       "answers": ["The United States",
                                   "The flag"]}},
           {"question": "What is the head executive of a state government called?",
            "answer": "Governor"},
           {"question": "Who is the Governor of your state now?",
            "answer": "Gary Herbert"},
           {
               "question": "What are two rights of everyone living in the United States?",
               "answer": {"type": "subset",
                          "size": 2,
                          "answers": ["freedom of expression",
                                      "freedom of speech",
                                      "freedom of assembly",
                                      "freedom of worship",
                                      "to petition the government",
                                      "the right to bear arms"]}
           },
           {
               "question": "What is one responsibility that is only for United States Citizens?",
               "answer": {"type": "subset",
                          "size": 1,
                          "answers": ["serve on a jury",
                                      "vote in a federal election"]
                         }},
           {
               "question": "What is the capital of your state?",
               "answer": "Salt Lake"
           },
           {
               "question": "What are the two major political parties in the United States?",
               "answer": {"type": "multi-part",
                          "answers": ["Democratic",
                                      "Republican"]
                         }
           },
           {
               "question": "What is the political party of the President now?",
               "answer": "Republican"
           },
           {
               "question": "There are four amendments to the Constitution about who can vote.  Describe one of them?",
               "answer": {"type": "subset",
                          "size": 1,
                          "answers": ["Citizens 18 and older can vote",
                                      "Any citizen (male or female) can vote",
                                      "You don't have to pay to vote",
                                      "Any citizen of any race can vote"]}
           },
           {
               "question": "Name one benefit of being a citizen of the United States",
               "answer": {"type": "subset",
                          "size": 1,
                          "answers": ["Obtain federal government jobs",
                                      "travel with a U.S. Passport",
                                      "petition for close relatives to come to the U.S."]}
           },
           {
               "question": "What is the name of the Speaker of the House?",
               "answer": "Paul Ryan"
           }
          ],

        "Quiz 14":
        [{"question": "There are 4 amendments to the Constitution about who can vote.  Name one of them.",
         "answer": "Citizens 18 and older can vote.\nAny citizen (male or female) can vote.\nYou don't have to pay to vote.\nA citizen of any race may vote."},
        {"question": "Name the amendments that address voting rights",
        "answer": "15, 19 and 24"},
        {"question": "What is one responsibility that is only for United States Citizens",
        "answer": "Serve on a jury.\nVote in a federal election."},
         {"question": "What are two rights of everyone living in the United States?",
          "answer": "Freedom of expression, speech, assembly, worship, petition the government and the right to bear arms."
         },
         {"question": "What do we show loyalty to when we say the pledge of Allegiance?",
          "answer": "The United States\nThe flag"},
         {
             "question": "Name one benefit of being a citizen of the United States",
             "answer": "to obtain Federal Government jobs\nto travel with a U.S. passport\nto petition for close relatives to come to the U.S. to live"
         }
        ],
    "Quiz 13":
     [{"question:": "Who is the chief justice of the United States?",
       "answer": "John Roberts"},
      {
          "question": "Under our constitution some powers belong to the states.  What is one power of the states?",
          "answer": "provide schooling and education, provide protection (police), provide safety (fire dept.), give a drivers license, approve zoning and land use"},
      {"question": "What is the head executive of a city government called?",
       "answer": "Mayor"
      },
      {
          "question": "What is the head executive of a state government called?",
          "answer": "Governor"
      },
      {
          "question": "Who is the governor of your state now?",
          "answer": "Gary Herbert"
      },
      {
          "question": "What is the capital of your state?",
          "answer": "Salt Lake City"
      },
      {
          "question": "What are the two major political parties in the United States?",
          "answer": "Democratic and Republican"
      },
      {
          "question": "What is the political party of the president now?",
          "answer": "Republican"
      },
      {
          "question": "What is the name of the Speaker of the House of Representatives now?",
          "answer": "John Boehner"
      }],
       "Test 8":
     [{"question": "What are some of the requirements to be eligible to become president?Quiz 11",
       "answer": "Must be at least 35 years old, must be born in the U.S., must have lived in the U.S. for at least 14 years."},
      {
          "question": "How many justices are on the supreme court?",
          "answer": "9"
      },
      {
          "question": "Name the highet part of the judiciary branch of the government",
          "answer": "The supreme court"
      },
      {
          "question": "What is the name of the president's official home?",
          "answer": "The White House"
      },
      {
          "question": "In what month do we vote for president?",
          "answer": "November"
      },
      {
          "question": "What is the highest court in the United States?",
          "answer": "The Supreme Court"
      },
      {
          "question": "In what month is the new president inaugurated?",
          "answer": "January"
      },
      {
          "question": "What does the president's cabinet do?",
          "answer": "Advises the president"
      },
      {
          "question": "What is the name of the President of the United States now?",
          "answer": "Donald Trump"
      },
      {
          "question": "What is the name of the vice president of the United States now?",
          "answer": "Mike Pence"
      },
      {
          "question": "Who nominates judges for the Supreme Court?",
          "answer": "The President"
      },
      {
          "question": "If the president can no longer serve who becomes president?",
          "answer": "The vice president"
      },
      {
          "question": "What are two cabinet level positions?",
          "answer": "Secretaries of: Agriculture, Commerce, Defense, Education, Energy, Health and Human Services, Homeland Security, Housing and Urban Development, Interior, Labor, State, Transportation, Treasury, Veteran's Affairs, Attorney General, Vice President"
      },
      {
          "question": "If the President and vice President can no longer serve who becomes president?",
          "answer": "The speaker of the house"
      },
      {
          "question": "What does the judicial branch do?",
          "answer": "reviews laws, resolves disagreements, explains laws, decides if laws go against the constitution"
      },
      {
          "question": "Where is the White House located?",
          "answer": "Washington D.C."
      },
      {
          "question": "Who is the commander in chief of the military?",
          "answer": "The president"
      }],
     "Quiz 11":
     [{"question": "What does the President's cabinet do?",
       "answer": "Advises the president"},
      {"question": "What are two Cabinet level positions?",
       "answer": "Secretaries of: Agriculture, Commerce, Defense, Education, Energy, Health and Human Services, Homeland Security, Housing and Urban Development, Interior, Labor, State, Transportation, Treasury, Veteran's Affairs, Attorney General, Vice President"},
      {"question": "What is the name of the President's official home?",
       "answer": "The White House"},
      {"question": "What does the Judicial branch do?",
       "answer": "reviews laws, resolves disagreements, explains laws, decides if laws go againts the constitution"},
      {"question": "What is the highest court in the United States?",
       "answer": "The supreme court"},
      {"question": "How many justices are on the Supreme Court?",
       "answer": "9"},
      {"question": "Who nominates judges for the Supreme Court?",
       "answer": "The President"},
      {"question": "Name the highest part of Judiciary Branch of Government.",
       "answer": "The Supreme Court"},
      {"question": "Where is the White House located?",
       "answer": "Washington D.C."}],
      "Test 7":
        [{"question": "What is the legislative branch of our Government?",
          "answer": "Congress"},
         {"question": "We elect a US Representative for how many years?",
          "answer": "2"},
         {"question": "Who does a US Senator represent?",
          "answer": "All the people of the state"},
         {"question": "Name your state's US Representatives:",
          "answer": "Jason Chaffetz, Mia Love, Chris Stewart, Rob Bishop"},
         {"question": "What are some of the basic beliefs of the Declaration of Independence?",
          "answer": "All men are created equal and have the right to life, liberty and the pursuit of happiness."},
         {"question": "Who elects the President of the United States?",
          "answer": "The Electoral College"},
         {"question": "How many branches are there in the United States Government?",
          "answer": "3"},
         {"question": "What is freedom of religion?",
          "answer": "You can practice any religion or not practice a religion."},
         {"question": "We elect a President for how many years?",
          "answer": "4 years for up to two terms"},
         {"question": "Who vetoes bills?",
          "answer": "The President"},
         {"question": "Who signs bills to become laws?",
          "answer": "The President"},
         {"question": "We elect a US Senator for how many years?",
          "answer": "6"},
         {"question": "What is the economic system in the United States",
          "answer": "Capitalist Economy, Market Economy"},
         {"question": "Who makes federal laws?",
          "answer": "Congress"},
         {"question": "What kind of government does the United States have?",
          "answer": "a Republic"},
         {"question": "What is the rule of law?",
          "answer": "Everyone must follow the law, even leaders and government, no one is above the law."},
         {"question": "Who elects Congress?",
          "answer": "U.S. Citizens"},
         {"question": "Who meets in the US Capitol building?",
          "answer": "Congress"},
         {"question": "Name the three branches or parts of the government.",
          "answer": "Legislative, Judicial, Executive"},
         {"question": "Where was the constitutional convention held?",
          "answer": "Philadelphia, Pennsylvania"},
         {"question": "What are the two parts of the US Congress?",
          "answer": "The Senate and the House of Representatives"},
         {"question": "What group has the power to declare war?",
          "answer": "Congress"},
         {"question": "How many US Senators are there?",
          "answer": "100"},
         {"question": "Name two signers of the Declaration of Independence",
          "answer": "John Hancock, Benjamin Franklin, John Adams, Samuel Adams, Thomas Jefferson"},
         {"question": "How many times may a senator or Congressman be re-elected",
          "answer": "no limit"},
         {"question": "What stops one branch of government from becoming too powerful?",
          "answer": "Checks and balances, separation of powers"},
         {"question": "Why do some states have more representatives than other states?",
          "answer": "Because of the states population, some states have more people"},
         {"question": "Who is in charge of the executive branch?",
          "answer": "The president"},
         {"question": "What is freedom of speech?",
          "answer": "You have the right to express any opinion without government interference."},
         {"question": "The house of representatives has how many voting members?",
          "answer": "435"},
         {"question": "Who are your states US Senators now?",
          "answer": "Orrin Hatch and Mike Lee"},
         {"question": "The Bill of Rights is made of how many ammendments?",
          "answer": "10"},
        ]
    };
