var flashcards = 
    {"Quiz 11":
     [{"question": "What does the President's cabinet do?",
       "answer": "Advises the president"},
      {"question": "What are two Cabinet level positions?",
       "answer": "Secretaries of: Agriculture, Commerce, Defense, Education, Energy, Health and Human Services, Homeland Security, Housing and Urban Development, Interior, Labor, State, Transportation, Treasury, Veteran's Affairs, Attorney General, Vice President"},
      {"question": "What is the name of the President's official home?",
       "answer": "The White House"},
      {"question": "What does the Judicial branch do?",
       "answer": "reviews laws, resolves disagreements, explains laws, decides if laws go againts the constitution"},
      {"question": "What is the highest court in the United States?",
       "answer": "The supreme court"},
      {"question": "How many justices are on the Supreme Court?",
       "answer": "9"},
      {"question": "Who nominates judges for the Supreme Court?",
       "answer": "The President"},
      {"question": "Name the highest part of Judiciary Branch of Government.",
       "answer": "The Supreme Court"},
      {"question": "Where is the White House located?",
       "answer": "Washington D.C."}],
      "Test 7":
        [{"question": "What is the legislative branch of our Government?",
          "answer": "Congress"},
         {"question": "We elect a US Representative for how many years?",
          "answer": "2"},
         {"question": "Who does a US Senator represent?",
          "answer": "All the people of the state"},
         {"question": "Name your state's US Representatives:",
          "answer": "Jason Chaffetz, Mia Love, Chris Stewart, Rob Bishop"},
         {"question": "What are some of the basic beliefs of the Declaration of Independence?",
          "answer": "All men are created equal and have the right to life, liberty and the pursuit of happiness."},
         {"question": "Who elects the President of the United States?",
          "answer": "The Electoral College"},
         {"question": "How many branches are there in the United States Government?",
          "answer": "3"},
         {"question": "What is freedom of religion?",
          "answer": "You can practice any religion or not practice a religion."},
         {"question": "We elect a President for how many years?",
          "answer": "4 years for up to two terms"},
         {"question": "Who vetoes bills?",
          "answer": "The President"},
         {"question": "Who signs bills to become laws?",
          "answer": "The President"},
         {"question": "We elect a US Senator for how many years?",
          "answer": "6"},
         {"question": "What is the economic system in the United States",
          "answer": "Capitalist Economy, Market Economy"},
         {"question": "Who makes federal laws?",
          "answer": "Congress"},
         {"question": "What kind of government does the United States have?",
          "answer": "a Republic"},
         {"question": "What is the rule of law?",
          "answer": "Everyone must follow the law, even leaders and government, no one is above the law."},
         {"question": "Who elects Congress?",
          "answer": "U.S. Citizens"},
         {"question": "Who meets in the US Capitol building?",
          "answer": "Congress"},
         {"question": "Name the three branches or parts of the government.",
          "answer": "Legislative, Judicial, Executive"},
         {"question": "Where was the constitutional convention held?",
          "answer": "Philadelphia, Pennsylvania"},
         {"question": "What are the two parts of the US Congress?",
          "answer": "The Senate and the House of Representatives"},
         {"question": "What group has the power to declare war?",
          "answer": "Congress"},
         {"question": "How many US Senators are there?",
          "answer": "100"},
         {"question": "Name two signers of the Declaration of Independence",
          "answer": "John Hancock, Benjamin Franklin, John Adams, Samuel Adams, Thomas Jefferson"},
         {"question": "How many times may a senator or Congressman be re-elected",
          "answer": "no limit"},
         {"question": "What stops one branch of government from becoming too powerful?",
          "answer": "Checks and balances, separation of powers"},
         {"question": "Why do some states have more representatives than other states?",
          "answer": "Because of the states population, some states have more people"},
         {"question": "Who is in charge of the executive branch?",
          "answer": "The president"},
         {"question": "What is freedom of speech?",
          "answer": "You have the right to express any opinion without government interference."},
         {"question": "The house of representatives has how many voting members?",
          "answer": "435"},
         {"question": "Who are your states US Senators now?",
          "answer": "Orrin Hatch and Mike Lee"},
         {"question": "The Bill of Rights is made of how many ammendments?",
          "answer": "10"},
        ]
    };
